version: "3.7"
   
services:
  jenkins-docker:
    hostname: jenkins-docker
    image: docker:dind
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkins
    ports:
      - "2376:2376"

  jenkins-blueocean:
    hostname: jenkins-blueocean
    image: myjenkins-blueocean:1.1
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    networks:
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins-docker-certs:
  jenkins-data:
networks:
  jenkins:
